apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels: 
        app: backend
    spec:
      containers:
      - name: chatapp-backend
        image: iemafzal/backend:v1
        ports:
        - containerPort: 5001
        env:
        # ✅ App expects MONGODB_URI (not MONGODB_URL)
        - name: MONGODB_URI
          value: "mongodb://mongoadmin:secret@mongo:27017/dbname?authSource=admin"

        - name: NODE_ENV
          value: production

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: chatapp-secrets
              key: jwt

        - name: PORT
          value: "5001"
